eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://ensaregistry-serv.herokuapp.com/eureka/
  instance:
    preferIpAddress: true
      
#defaultZone: https://ensaregistry-serv.herokuapp.com/eureka/
#defaultZone: http://localhost:8761/eureka
